image:
  name: 'hashicorp/terraform:light'
  entrypoint:
    - /usr/bin/env
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
before_script:
  - 'cd ${CI_PROJECT_DIR}/terraform'
  - rm -rf .terraform
  - terraform --version
  - echo $GCP_SERVICE_ACCOUNT | base64 -d > creds.json
  - terraform init

stages:
  - validate
  - plan
  - apply

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out "planfile"
  artifacts:
    paths:
    - terraform/planfile
  needs:
    - validate

apply:
  stage: apply
  script:
    - terraform apply -input=false "planfile"
  dependencies: 
    - plan
  needs:
    - plan
  when: manual
